FROM registry.fedoraproject.org/fedora:33

WORKDIR /zig

RUN dnf update -y && dnf install -y curl jq sqlite sqlite-devel xz bash

RUN curl -L -s "https://ziglang.org/download/index.json" | jq '.master["x86_64-linux"].tarball' -r >> /zig/zig_master_url
RUN curl -J -o /zig/zig.tar.xz $(cat /zig/zig_master_url)
RUN tar xJf /zig/zig.tar.xz
RUN ls -lh /zig
RUN mv /zig/zig-linux-* /zig/zig-master

WORKDIR /work

COPY *.zig .
COPY c c

ENTRYPOINT ["/bin/bash"]
