name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        zig_version: ["0.16.0", "0.17.0"]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig_version }}
      - run: zig fmt --check *.zig

  test-in-memory:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]
        zig_version: ["0.16.0", "0.17.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig_version }}

      - name: Install qemu
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y qemu-user-binfmt

      - name: Run Tests in memory
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: |
          mkdir -p $ZIG_GLOBAL_CACHE_DIR/tmp
          zig build test -Dci=true -Din_memory=true --summary all -fqemu -fwine
      - name: Run Tests in memory
        if: ${{ matrix.os != 'ubuntu-24.04' }}
        run: |
          mkdir -p $ZIG_GLOBAL_CACHE_DIR/tmp
          zig build test -Dci=true -Din_memory=true --summary all